### ISSUE TITLE
Recompile for Node.js 8.10

### ISSUE THREAD

**Issue by davidroman0O** [chunyenHuang/hummusRecipeForLambda#1]
Hi!

Thx for the package, it works well for 6.10!

Is there a possibility that you re-compile Hummus/HummusRecipe for 8.10 on a new repos?

Would be great to use async functions! I don't know a lot about docker so using docker-lambda and do it myself would be a bit long!

Hope you will anwser to this issue :)

**Comment by yusufyildirim** [comment]
You can download for 8.10 version down below.
https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.82/node-v57-linux-x64.tar.gz

Also, v1.0.88 is the latest version of the Hummus library. So, if you want to download the latest version, you can change 1.0.82 part from the URL with 1.0.88 (or any other version)

**Comment by davidroman0O** [comment]
Wow thx a lot, i'm gonna test it this week!

**Comment by davidroman0O** [comment]
* several months later *

Finally tested it, it's working !

My sh file at the root of the node project : 

```bash

rm -rf node_modules/hummus
rm -rf node_modules/hummus-recipe

mkdir node_modules/hummus
mkdir node_modules/hummus-recipe

cp -r ../../libraries/node8.10/hummus/* ./node_modules/hummus
cp -r ../../libraries/node8.10/hummus-recipe/* ./node_modules/hummus-recipe

```

hummus@1.0.82
hummus-recipe@1.2.5
